version: 2
jobs:
  build:
    parallelism: 1
    working_directory: ~/clickx
    docker:
      - image: circleci/ruby:2.5.1-node-browsers
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          PGHOST: 127.0.0.1
          PGUSER: postgres
          RAILS_ENV: test
          CLOUDINARY_URL: "cloudinary://767931274478368:GlkuRZtYEq0ApKqh4ep7ZpcY3Jk@htro6l1zt"
          SNIP_URL: "somedomain.dev"
      - image: circleci/postgres:9.4-alpine-ram
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: clickx_test
          POSTGRES_PASSWORD: postgres
    steps:
      - checkout

      # Which version of bundler?
      - run:
          name: Which bundler?
          command: bundle -v

      # Restore bundle cache
      - restore_cache:
          keys:
            - clickx-bundle-v2-{{ checksum "Gemfile.lock" }}
            - clickx-bundle-v2-
      - run:
              name: install dependencies
              command: |
                      sudo apt-get update
                      sudo apt-get install libidn11-dev
                      sudo apt-get install qt5-default libqt5webkit5-dev gstreamer1.0-plugins-base gstreamer1.0-tools gstreamer1.0-x
                      sudo apt-get install cmake

      - run:
          name: Bundle Install
          command:  |
                    bundle update active_model_serializers
                    bundle update better_errors
                    bundle check || bundle install --jobs=4 --retry=3 --path vendor/bundle --without development production

      # Store bundle cache
      - save_cache:
          key: clickx-bundle-v2-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # Only necessary if app uses webpacker or yarn in some other way
      - restore_cache:
          keys:
            - clickx-yarn-{{ checksum "yarn.lock" }}
            - clickx-yarn-

      - run:
          name: Yarn Install
          command: yarn install --cache-folder ~/.cache/yarn

      # Store yarn / webpacker cache
      - save_cache:
          key: clickx-yarn-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn

      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Database setup
          command: bin/rails db:schema:load --trace

      - run:
          name: Bundle audit
          command: bundle exec bundle audit


      # Run rspec in parallel
      - type: shell
        command: |
          # bundle exec cucumber features

      - type: shell
        command: |
          bundle exec rspec --profile 10 \
                            --format RspecJunitFormatter \
                            --out test_results/rspec.xml \
                            --format progress \
                            $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)

      # Save test results for timing analysis
      - store_test_results:
          path: test_results
