class Industry < ApplicationRecord
  has_many :case_study_industries
  has_many :case_studies, through: :case_study_industries
  has_many :favorite_industries, dependent: :destroy
  has_many :favorited_users, through: :favorite_industries, class_name: 'User', source: :user
  has_many :funnel_pages
  has_one :funnel_page, -> { merge(FunnelPage.published) }

  has_many :agency_niches, dependent: :destroy, class_name: 'AgencyNiche'

  validates :title, presence: true

  ICONS = [
    'Accounting',
    'Acupuncturist',
    'Agriculture',
    'Apparel',
    'Architecture',
    'Arts-Entertainment',
    'Assisted-Living',
    'Attorney-Law-Firm',
    'Auto',
    'Auto-Repair',
    'Aviation',
    'Beauty',
    'Beauty-Salon-Hair-Stylist',
    'Bigcommerce',
    'Business',
    'Business-Services',
    'Camera',
    'Car',
    'Car-1',
    'Carpet-Cleaning',
    'Catering',
    'Child-Care',
    'Child-Care1',
    'Chiropractor',
    'Cleaning',
    'Computers',
    'Construction',
    'Dance',
    'Dance-2',
    'Dance-School',
    'Dating',
    'Dentist',
    'Doctor',
    'Ecommerce',
    'eCommerceRetail',
    'Education',
    'Electrician',
    'Electricity-Tower',
    'Electronics',
    'Energy',
    'Engineering',
    'Fence-Contractor',
    'Financial',
    'Financial-2',
    'Financial-Advisor',
    'Fitness',
    'Fitness-2',
    'Fitness-Personal-Trainer',
    'Fitness-Yoga',
    'Flooring',
    'Food-Beverage-Manufacturing',
    'Franchises',
    'Franchises-2',
    'Franchises1',
    'Funeral-Home',
    'Garage-1',
    'Garage-2',
    'Garbage-Waste',
    'Gas-Bottle',
    'Gas-Detection',
    'Gas-Pump',
    'General-Contractor',
    'Glass-Company',
    'Handyman',
    'Health-Wellness',
    'Healthcare',
    'Healthcare-2',
    'Home-Decor',
    'Home-Decor-2',
    'Home-Health-Care',
    'Home-Renovation',
    'Home-Services',
    'Home-Services-2',
    'Hospitality',
    'House-Cleaning',
    'HVAC',
    'HVAC-2',
    'HVAC-3',
    'HVAC1',
    'Industrial',
    'Industrial-2',
    'Information-Technology',
    'Insurance',
    'Insurance-2',
    'Interior-Design',
    'Janitorial',
    'Jewelry',
    'Jewelry-2',
    'Landscaping',
    'Landscaping1',
    'Lawn-Care',
    'Legal',
    'Legal-2',
    'Limo-Service',
    'Locksmith',
    'Luggage',
    'Machinery',
    'Machinery-2',
    'Manufacturing',
    'Manufacturing-2',
    'Massage-Therapist',
    'Medical',
    'Medical-2',
    'Medical1',
    'Medspa',
    'Mentor',
    'Motivational-Coaches',
    'Moving-Service',
    'Music',
    'Music-2',
    'Non-Profit',
    'Online-Business',
    'Online-Business-2',
    'Online-Class',
    'Online-Course',
    'Optometrist-Eye-Doctor',
    'Painting',
    'Personal-Development',
    'Personal-Development-2',
    'Pest-Control',
    'Plastic-Surgeon',
    'Plumbing',
    'Plumbing-2',
    'Plumbing1',
    'Private-Investigator',
    'Professions-And-Jobs',
    'Real-Estate',
    'Real-Estate-2',
    'Real-Estate1',
    'Restaurant',
    'Retail',
    'Retail-2',
    'Roofer',
    'Roofing',
    'Roofing-2',
    'SaaS',
    'Self-Storage',
    'Shipping',
    'Sign-Company',
    'Software',
    'Solar-Energy',
    'Solar-Energy-2',
    'Solar-Energy1',
    'Spa',
    'Sports',
    'Sports-2',
    'Swimming-Pool-Service',
    'Telecommunications',
    'Telecommunications-2',
    'Therapist-Psychiatrist',
    'Tour-Bus',
    'Tourism',
    'Transportation',
    'Transportation-2',
    'Travel',
    'Travel1',
    'Tree-Care',
    'Veterinarian',
    'Veterinary-Services',
    'Veterinary-Services-2',
    'Video-Lecture',
    'Wind-Power'
  ]

  before_destroy :mover_case_studies_to_others

  def self.other
    self.find_by title: 'Others'
  end

  private

  def mover_case_studies_to_others
    other = Industry.other
    raise '`Others` industry not exists. Please create.' unless other

    case_studies.update_all industry_id: other.id
  end
end
